AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: |
  sam-crypto
  Sample SAM Template for sam-crypto
Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - staging
      - prod
    Default: dev
  ApiStageName:
    Type: String
    Default: dev
  CoinGeckoSecretName:
    Type: String
    Default: coingecko_secret
  CoinGeckoBaseUrl:
    Type: String
    Default: https://api.coingecko.com/api/v3
Globals:
  Function:
    Timeout: 10
    LoggingConfig:
      LogFormat: JSON
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref ApiStageName
 
  CoinGeckoTopCoinsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/modules/coingecko
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          COINGECKO_BASE_URL: !Ref CoinGeckoBaseUrl
          COINGECKO_SECRET_NAME: !Ref CoinGeckoSecretName
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
                - secretsmanager:ListSecrets
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${CoinGeckoSecretName}*
      Events:
        CoinGeckoTopCoins:
          Type: Api
          Properties:
            Path: /top-coins
            Method: get
            RestApiId: !Ref MyApi
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
Outputs:
  CoinGeckoTopCoinsFunctionApi:
    Description: API Gateway endpoint URL for ${ApiStageName} stage for crypto function
    Value: !Sub https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/${ApiStageName}/top-coins/
  CoinGeckoTopCoinsFunction:
    Description: crypto Lambda Function ARN
    Value: !GetAtt CoinGeckoTopCoinsFunction.Arn
  CoinGeckoTopCoinsFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt CoinGeckoTopCoinsFunctionRole.Arn
