version = 0.1
[dev.deploy.parameters]
stack_name = "sam-crypto-dev"
resolve_s3 = true
s3_prefix = "sam-crypto-dev"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\" ApiStageName=\"dev\" CoinGeckoSecretName=\"coingecko_secret\" CoinGeckoBaseUrl=\"https://api.coingecko.com/api/v3\" BinanceBaseUrl=\"https://api.binance.com\" BinanceSecretName=\"binance_secret\" TokeninsightBaseUrl=\"https://api.tokeninsight.com\" TokeninsightSecretName=\"tokeninsight_secret\""
image_repositories = []
