AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: |
  sam-crypto
  Sample SAM Template for sam-crypto
Parameters:
  Environment:
    Type: String
    AllowedValues:
    - dev
    - staging
    - prod
    Default: dev
  ApiStageName:
    Type: String
    Default: dev
  CoinGeckoSecretName:
    Type: String
    Default: coingecko_secret
  CoinGeckoBaseUrl:
    Type: String
    Default: https://api.coingecko.com/api/v3
  BinanceBaseUrl:
    Type: String
    Default: https://api.binance.com
  BinanceSecretName:
    Type: String
    Default: binance_secret
  TokeninsightBaseUrl:
    Type: String
    Default: https://api.tokeninsight.com
  TokeninsightSecretName:
    Type: String
    Default: tokeninsight_secret
Globals:
  Function:
    Timeout: 10
    LoggingConfig:
      LogFormat: JSON
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref ApiStageName

  CoinGeckoTopCoinsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/modules/coingecko
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Environment:
        Variables:
          COINGECKO_BASE_URL: !Ref CoinGeckoBaseUrl
          COINGECKO_SECRET_NAME: !Ref CoinGeckoSecretName
      Policies:
      - Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - secretsmanager:GetSecretValue
          - secretsmanager:DescribeSecret
          - secretsmanager:ListSecrets
          Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${CoinGeckoSecretName}*
      Events:
        CoinGeckoTopCoins:
          Type: Api
          Properties:
            Path: /popular
            Method: get
            RestApiId: !Ref MyApi
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts

  BinanceListAllConvertPairsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/modules/binance/convert/list-all-convert-pairs
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Environment:
        Variables:
          BINANCE_BASE_URL: !Ref BinanceBaseUrl
      Events:
        CoinGeckoTopCoins:
          Type: Api
          Properties:
            Path: /list-all-covert-pairs
            Method: get
            RestApiId: !Ref MyApi
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
  BinanceListTicker24hrFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/modules/binance/list-ticker-24hr
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Environment:
        Variables:
          BINANCE_BASE_URL: !Ref BinanceBaseUrl
      Events:
        CoinGeckoTopCoins:
          Type: Api
          Properties:
            Path: /list-ticker-24hr
            Method: get
            RestApiId: !Ref MyApi
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
  BinanceSendQuoteRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/modules/binance/convert/send-quote-request
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Environment:
        Variables:
          BINANCE_BASE_URL: !Ref BinanceBaseUrl
          BINANCE_SECRET_NAME: !Ref BinanceSecretName
      Policies:
      - Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - secretsmanager:GetSecretValue
          - secretsmanager:DescribeSecret
          - secretsmanager:ListSecrets
          Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${BinanceSecretName}*
      Events:
        CoinGeckoTopCoins:
          Type: Api
          Properties:
            Path: /send-quote-request
            Method: post
            RestApiId: !Ref MyApi
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts

  TokeninsightTopGainersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/modules/tokeninsight/top-gainers
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Environment:
        Variables:
          TOKENINSIGHT_BASE_URL: !Ref TokeninsightBaseUrl
          TOKENINSIGHT_SECRET_NAME: !Ref TokeninsightSecretName
      Policies:
      - Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - secretsmanager:GetSecretValue
          - secretsmanager:DescribeSecret
          - secretsmanager:ListSecrets
          Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${TokeninsightSecretName}*
      Events:
        CoinGeckoTopCoins:
          Type: Api
          Properties:
            Path: /top-coins
            Method: get
            RestApiId: !Ref MyApi
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
  TokeninsightTopLosersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/modules/tokeninsight/top-losers
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Environment:
        Variables:
          TOKENINSIGHT_BASE_URL: !Ref TokeninsightBaseUrl
          TOKENINSIGHT_SECRET_NAME: !Ref TokeninsightSecretName
      Policies:
      - Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - secretsmanager:GetSecretValue
          - secretsmanager:DescribeSecret
          - secretsmanager:ListSecrets
          Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${TokeninsightSecretName}*
      Events:
        CoinGeckoTopCoins:
          Type: Api
          Properties:
            Path: /top-losers
            Method: get
            RestApiId: !Ref MyApi
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
Outputs:
  CoinGeckoTopCoinsFunctionApi:
    Description: API Gateway endpoint URL for ${ApiStageName} stage for crypto function
    Value: !Sub https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/${ApiStageName}/top-coins/
  CoinGeckoTopCoinsFunction:
    Description: crypto Lambda Function ARN
    Value: !GetAtt CoinGeckoTopCoinsFunction.Arn
  CoinGeckoTopCoinsFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt CoinGeckoTopCoinsFunctionRole.Arn
